/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Movie = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'quality' : IDL.Text,
  'description' : IDL.Text,
  'downloadUrl' : IDL.Text,
  'genre' : IDL.Text,
  'posterUrl' : IDL.Text,
  'category' : IDL.Text,
  'videoUrl' : IDL.Text,
  'releaseDate' : IDL.Text,
  'runtime' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMovie' : IDL.Func([Movie], [], []),
  'deleteMovie' : IDL.Func([IDL.Nat], [], []),
  'getMovieById' : IDL.Func([IDL.Nat], [Movie], ['query']),
  'getMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
  'getMoviesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
  'updateMovie' : IDL.Func([IDL.Nat, Movie], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Movie = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'quality' : IDL.Text,
    'description' : IDL.Text,
    'downloadUrl' : IDL.Text,
    'genre' : IDL.Text,
    'posterUrl' : IDL.Text,
    'category' : IDL.Text,
    'videoUrl' : IDL.Text,
    'releaseDate' : IDL.Text,
    'runtime' : IDL.Text,
  });
  
  return IDL.Service({
    'addMovie' : IDL.Func([Movie], [], []),
    'deleteMovie' : IDL.Func([IDL.Nat], [], []),
    'getMovieById' : IDL.Func([IDL.Nat], [Movie], ['query']),
    'getMovies' : IDL.Func([], [IDL.Vec(Movie)], ['query']),
    'getMoviesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Movie)], ['query']),
    'updateMovie' : IDL.Func([IDL.Nat, Movie], [], []),
  });
};

export const init = ({ IDL }) => { return []; };